name: CI Pipeline - Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Tarea 1: Descargar dependencias - Python y Node.js
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    # Instalar dependencias del backend
    - name: Install Python dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    # Instalar dependencias del frontend
    - name: Install Node.js dependencies
      run: |
        cd frontend
        npm clean-install || npm install
        npm ls react-scripts || npm install react-scripts@5.0.1
        
